title : Anydiver Tutorial
tagline: Blog Tagline
author :
  name : Fred Schoeneman
  email : fred@anydiver.com
  github : fdschoeneman
  twitter : fdschoeneman
  feedburner : 

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
